apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: pe-hackathon
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: discord
      group_by: ['alertname', 'severity']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 4h

    receivers:
      - name: discord
        webhook_configs:
          - url: http://dashboard-backend:8000/api/alertmanager-webhook
            send_resolved: true
