apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pe-hackathon

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - pvc-backups.yaml
  - configmap-url-shortener.yaml
  - deployment-url-shortener-a.yaml
  - deployment-url-shortener-b.yaml
  - service-url-shortener-a.yaml
  - service-url-shortener-b.yaml
  - deployment-load-balancer.yaml
  - service-load-balancer.yaml
  - rbac-prometheus.yaml
  - configmap-prometheus.yaml
  - deployment-prometheus.yaml
  - service-prometheus.yaml
  - configmap-alertmanager.yaml
  - deployment-alertmanager.yaml
  - service-alertmanager.yaml
  - cronjob-db-backup.yaml
  - deployment-dashboard.yaml
  - service-dashboard.yaml
  - deployment-user-frontend.yaml
  - service-user-frontend.yaml
  - hpa-url-shortener-a.yaml
  - hpa-url-shortener-b.yaml

commonLabels:
  app.kubernetes.io/part-of: pe-hackathon-2026

images:
  - name: pe-hackathon/url-shortener
    newTag: latest
  - name: pe-hackathon/load-balancer
    newTag: latest
  - name: pe-hackathon/dashboard
    newTag: latest
  - name: pe-hackathon/user-frontend
    newTag: latest
