apiVersion: v1
kind: Service
metadata:
  name: url-shortener-b
  namespace: pe-hackathon
  labels:
    app: url-shortener-b
spec:
  type: ClusterIP
  selector:
    app: url-shortener-b
  ports:
    - name: http
      port: 5000
      targetPort: http
