apiVersion: v1
kind: Service
metadata:
  name: user-frontend
  namespace: pe-hackathon
  labels:
    app: user-frontend
spec:
  type: NodePort
  selector:
    app: user-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30002
