apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: pe-hackathon
  labels:
    app: alertmanager
spec:
  type: NodePort
  selector:
    app: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http
      nodePort: 30993
